name: GPU Passthrough
description: ''
featureId: terminus-infra-gpu-passthrough
featureSlug: gpu-passthrough
domain: terminus
service: infra
phase: dev-complete
track: tech-change
milestones:
  businessplan: null
  techplan: '2026-04-25T18:02:34Z'
  finalizeplan: '2026-04-26T00:00:00Z'
  dev-ready: '2026-04-25T18:02:34Z'
  dev-complete: '2026-04-26T00:00:00Z'
  completed: '2026-04-26T00:00:00Z'
team:
- username: Todd Hintzmann
  role: lead
dependencies:
  depends_on: []
  depended_by: []
target_repos: []
links:
  retrospective: null
  issues: []
  pull_request: 'https://github.com/electricm0nk/bmad.lens.projects/pull/190'
  final_pr: 'https://github.com/electricm0nk/terminus.infra/pull/120'
priority: medium
created: '2026-04-25T17:33:02Z'
updated: '2026-04-26T01:00:00Z'
phase_transitions:
- phase: techplan
  timestamp: '2026-04-25T17:33:02Z'
  user: Todd Hintzmann
- phase: techplan-complete
  timestamp: '2026-04-25T18:02:34Z'
  user: Todd Hintzmann
- phase: finalizeplan-complete
  timestamp: '2026-04-26T00:00:00Z'
  user: Todd Hintzmann
- phase: dev-complete
  timestamp: '2026-04-26T00:00:00Z'
  user: conductor
- phase: completed
  timestamp: '2026-04-26T01:00:00Z'
  user: conductor
docs:
  path: docs/terminus/infra/terminus-infra-gpu-passthrough
  governance_docs_path: features/terminus/infra/terminus-infra-gpu-passthrough/docs
