name: Proxmox
description: 'Migrated from legacy branch: terminus-infra-proxmox'
featureId: proxmox
domain: terminus
service: infra
phase: preplan
track: full
milestones:
  businessplan: null
  techplan: null
  finalizeplan: null
  dev-ready: null
  dev-complete: null
team:
- username: Todd Hintzmann
  role: lead
dependencies:
  depends_on: []
  depended_by: []
target_repos:
- name: terminus.infra
  url: https://github.com/electricm0nk/terminus.infra.git
  remote_url: https://github.com/electricm0nk/terminus.infra.git
  local_path: TargetProjects/terminus/infra/terminus.infra
  branch: main
  default_branch: main
  dev_branch_mode: direct-default
links:
  retrospective: null
  issues: []
  pull_request: null
priority: medium
created: '2026-04-14T20:31:27Z'
updated: '2026-04-26T12:57:37Z'
phase_transitions:
- phase: preplan
  timestamp: '2026-04-14T20:31:27Z'
  user: Todd Hintzmann
docs:
  path: docs/terminus/infra/proxmox
  governance_docs_path: null
migrated_from: terminus-infra-proxmox
